### ISSUE TITLE
FizzBuzz!

### ISSUE THREAD

**Issue by bgates** [tiy-orl/front-end-quiz#28]
This is an old interview question. Write code for it in a separate file, `fizzbuzz.js`. Here's what it should do:

* iterate over every integer from 1 to 100
* print out each integer to the console, except:
  * if a number is divisible by 3, instead of the number, print 'fizz'
  * if a number is divisible by 5, instead of the number, print 'buzz'
  * and most important, if a number is divisible by 3 and 5, instead of the number, print 'fizzbuzz'

**Comment by tyjdavis** [comment]
fixed issue

**Comment by WJWJR** [comment]
Added my version
